sonar.projectKey=fullstack-devops-automation
sonar.projectName=fullstack-devops-automation
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.md
sonar.sourceEncoding=UTF-8